name: Bug report / バグ報告
description: Create a report to help us improve
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for reporting the bug. Please fill in the following information.

    - type: textarea
      id: description
      attributes:
          label: Bug Summary / バグの概要
          description: A clear and concise description of what the bug is.
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: To Reproduce / 再現手順
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true

    - type: input
      id: extVersion
      attributes:
          label: Extension Version / 拡張機能のバージョン
          description: The version of the extension you are using.
          placeholder: 2.2.0
      validations:
          required: true

    - type: dropdown
      id: browsers
      attributes:
          label: Browser
          multiple: true
          options:
              - Chrome
              - Edge
              - Firefox
              - Other
      validations:
          required: true
